### PR TITLE
Fix running Dracnmap with sudo

### PR DESCRIPTION
**Pull request by nullrndtx**
i just trying to help you :dancing_men: 

BEFORE

can run with this parameter sudo ./Dracnmap.sh

Before

AFTER:

now can run with sudo ./Dracnmap.sh

After

### CODE REVIEW

**Comment by screetsec** [comment]
thanks kang randal

**Comment by misterbee2856** [comment]
newbie kang...hehe...
tujuan si software nya buat apa kang..?
kaya angry ip..?
nyeken ip yang sejaringan sama kita apa gimana..?hehhe

**Comment by screetsec** [comment]
Scanning ip target isa diluar jaringan juga bisa ( web )

**Comment by misterbee2856** [comment]
oks thanks....ga ada link git clone nya kang..?

**Comment by nullrndtx** [comment]
@misterbee2856 git clone https://github.com/Screetsec/Dracnmap && cd Dracnmap

may this solve your problems :)

**Pull request closed without merging**
